// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhMVvzJtP1q8CphfYhSlUEYNFlLl0_h3M',
    appId: '1:350085749202:web:a125c3d6e28651f3d7900b',
    messagingSenderId: '350085749202',
    projectId: 'flutter-application-1-76a03',
    authDomain: 'flutter-application-1-76a03.firebaseapp.com',
    storageBucket: 'flutter-application-1-76a03.appspot.com', // ✅ Fixed
    measurementId: 'G-1L1LWP6DXL',
    databaseURL: 'https://flutter-application-1-76a03-default-rtdb.firebaseio.com/', // ✅ Added
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9Ve7LucQCYPiDgHuizfLZvuJFmnJzck',
    appId: '1:350085749202:android:5dcd891a5c3e1696d7900b',
    messagingSenderId: '350085749202',
    projectId: 'flutter-application-1-76a03',
    storageBucket: 'flutter-application-1-76a03.appspot.com', // ✅ Fixed
    databaseURL: 'https://flutter-application-1-76a03-default-rtdb.firebaseio.com/', // ✅ Added
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVbdVOB2juqLBv73VGpDJ_Mpve8lYK6X0',
    appId: '1:350085749202:ios:a71ddef47e134824d7900b',
    messagingSenderId: '350085749202',
    projectId: 'flutter-application-1-76a03',
    storageBucket: 'flutter-application-1-76a03.appspot.com', // ✅ Fixed
    databaseURL: 'https://flutter-application-1-76a03-default-rtdb.firebaseio.com/', // ✅ Added
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVbdVOB2juqLBv73VGpDJ_Mpve8lYK6X0',
    appId: '1:350085749202:ios:a71ddef47e134824d7900b',
    messagingSenderId: '350085749202',
    projectId: 'flutter-application-1-76a03',
    storageBucket: 'flutter-application-1-76a03.appspot.com', // ✅ Fixed
    databaseURL: 'https://flutter-application-1-76a03-default-rtdb.firebaseio.com/', // ✅ Added
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhMVvzJtP1q8CphfYhSlUEYNFlLl0_h3M',
    appId: '1:350085749202:web:499ad70b9458cb71d7900b',
    messagingSenderId: '350085749202',
    projectId: 'flutter-application-1-76a03',
    authDomain: 'flutter-application-1-76a03.firebaseapp.com',
    storageBucket: 'flutter-application-1-76a03.appspot.com', // ✅ Fixed
    databaseURL: 'https://flutter-application-1-76a03-default-rtdb.firebaseio.com/', // ✅ Added
    measurementId: 'G-CHWXSPM56T',
  );
}
